In [29]:
# Loading the dataset using pandas

import pandas as pd

df = pd.read_csv("Amazon.csv")

In [19]:
df.head()

      OrderID   OrderDate  CustomerID   CustomerName ProductID  ... OrderStatus         City State        Country   SellerID
0  ORD0000001  2023-01-31  CUST001504  Vihaan Sharma    P00014  ...   Delivered   Washington    DC          India  SELL01967
1  ORD0000002  2023-12-30  CUST000178    Pooja Kumar    P00040  ...   Delivered   Fort Worth    TX  United States  SELL01298
2  ORD0000003  2022-05-10  CUST047516    Sneha Singh    P00044  ...   Delivered       Austin    TX  United States  SELL00908
3  ORD0000004  2023-07-18  CUST030059   Vihaan Reddy    P00041  ...   Delivered    Charlotte    NC          India  SELL01164
4  ORD0000005  2023-02-04  CUST048677  Aditya Kapoor    P00029  ...   Cancelled  San Antonio    TX         Canada  SELL01411

[5 rows x 20 columns]

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  str
 1   OrderDate      100000 non-null  str
 2   CustomerID     100000 non-null  str
 3   CustomerName   100000 non-null  str
 4   ProductID      100000 non-null  str
 5   ProductName    100000 non-null  str
 6   Category       100000 non-null  str
 7   Brand          100000 non-null  str
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  str
 15  OrderStatus    100000 non-null  str
 16  City           100000 non-null  str
 17  State          100000 non-null  str
 18  Country        100000 non-null  str
 19  SellerID       100000 non-null  str
dtypes: float64(5), int64(1), str(14)
memory usage: 27.5 MB

In [28]:
# Summary statistics using .describe()

df.describe(include='all')

           orderid   orderdate  customerid customername  ...       city   state        country   sellerid
count       100000      100000      100000       100000  ...     100000  100000         100000     100000
unique      100000        1825       43233          200  ...         20      13              5       1999
top     ORD0000001  2022-04-28  CUST023748  Karan Joshi  ...  Charlotte      TX  United States  SELL01099
freq             1          85          10          556  ...       5110   24896          70058         78
mean           NaN         NaN         NaN          NaN  ...        NaN     NaN            NaN        NaN
std            NaN         NaN         NaN          NaN  ...        NaN     NaN            NaN        NaN
min            NaN         NaN         NaN          NaN  ...        NaN     NaN            NaN        NaN
25%            NaN         NaN         NaN          NaN  ...        NaN     NaN            NaN        NaN
50%            NaN         NaN         NaN          NaN  ...        NaN     NaN            NaN        NaN
75%            NaN         NaN         NaN          NaN  ...        NaN     NaN            NaN        NaN
max            NaN         NaN         NaN          NaN  ...        NaN     NaN            NaN        NaN

[11 rows x 20 columns]

In [30]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

In [31]:
# Skip lowercasing the column names because it reduces readability.

# For example, 'OrderId' would become 'orderid', which is harder to read and distinguish.

# df.columns = df.columns.str.lower()

In [25]:
df.columns

Index(['orderid', 'orderdate', 'customerid', 'customername', 'productid',
       'productname', 'category', 'brand', 'quantity', 'unitprice', 'discount',
       'tax', 'shippingcost', 'totalamount', 'paymentmethod', 'orderstatus',
       'city', 'state', 'country', 'sellerid'],
      dtype='str')

## Connecting Python Script to MySql

In [ ]:
!pip install pymysql sqlalchemy

In [26]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "4748"
host = "localhost"
port = "3306"
database = "amazon_sales"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

      orderid   orderdate  customerid   customername productid  ... orderstatus         city state        country   sellerid
0  ORD0000001  2023-01-31  CUST001504  Vihaan Sharma    P00014  ...   Delivered   Washington    DC          India  SELL01967
1  ORD0000002  2023-12-30  CUST000178    Pooja Kumar    P00040  ...   Delivered   Fort Worth    TX  United States  SELL01298
2  ORD0000003  2022-05-10  CUST047516    Sneha Singh    P00044  ...   Delivered       Austin    TX  United States  SELL00908
3  ORD0000004  2023-07-18  CUST030059   Vihaan Reddy    P00041  ...   Delivered    Charlotte    NC          India  SELL01164
4  ORD0000005  2023-02-04  CUST048677  Aditya Kapoor    P00029  ...   Cancelled  San Antonio    TX         Canada  SELL01411

[5 rows x 20 columns]